FROM node:22-alpine
RUN apk add --no-cache \
      python3 make g++ \
      chromium nss freetype harfbuzz ca-certificates ttf-freefont \
      font-noto-emoji
WORKDIR /app
ENV PUPPETEER_SKIP_DOWNLOAD=true
ENV PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser
COPY package.json yarn.lock ./
RUN yarn install
COPY . .
ENV DATABASE_PATH=/data/db.sqlite
ENV EXPORT_DIR=/data/exports
EXPOSE 4000
CMD ["sh", "-c", "yarn install && yarn dev"]
